package org.aaa.mybatis.entity;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated Wed Aug 31 10:46:33 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ordertime
     *
     * @mbggenerated Wed Aug 31 10:46:33 CST 2022
     */
    private String ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.total
     *
     * @mbggenerated Wed Aug 31 10:46:33 CST 2022
     */
    private Double total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.uid
     *
     * @mbggenerated Wed Aug 31 10:46:33 CST 2022
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated Wed Aug 31 10:46:33 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated Wed Aug 31 10:46:33 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ordertime
     *
     * @return the value of orders.ordertime
     *
     * @mbggenerated Wed Aug 31 10:46:33 CST 2022
     */
    public String getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ordertime
     *
     * @param ordertime the value for orders.ordertime
     *
     * @mbggenerated Wed Aug 31 10:46:33 CST 2022
     */
    public void setOrdertime(String ordertime) {
        this.ordertime = ordertime == null ? null : ordertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.total
     *
     * @return the value of orders.total
     *
     * @mbggenerated Wed Aug 31 10:46:33 CST 2022
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.total
     *
     * @param total the value for orders.total
     *
     * @mbggenerated Wed Aug 31 10:46:33 CST 2022
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.uid
     *
     * @return the value of orders.uid
     *
     * @mbggenerated Wed Aug 31 10:46:33 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.uid
     *
     * @param uid the value for orders.uid
     *
     * @mbggenerated Wed Aug 31 10:46:33 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}